### ISSUE TITLE
Wiring diagram for ESP32 is incorrect

### ISSUE THREAD

**Issue by tobozo** [G6EJD/ESP32-8266-Audio-Spectrum-Display#1]
Thanks for this awesome work, so clear to read and simple to setup :+1: 

Wiring diagram for the ESP32 states that mic data pin is connected to "EN" but doing this triggers a reset loop (at least on my ESp32 Dev Kit rev 1).

According to the [pinout map](https://raw.githubusercontent.com/gojimmypi/ESP32/master/images/myESP32%20DevKitC%20pinout.png), A0 is on "SVP", just next to "EN".

Here's a "fixed" version of the wiring diagram for ESP32.

![image](https://user-images.githubusercontent.com/1893754/34071855-80287e80-e27d-11e7-9071-ccc0d40d4c8d.png)

**Comment by G6EJD** [comment]
Thank you spotting this error, that's twice I have done this, first was I miscounted the SDA,SCL pins and corrected those this morning and now VP was wrong. You should find (if your using the Arduino IDE) that A0 is the same as VP or you can use 36 all for the same analogue input port. Thanks for the amended diagram, corrected now in the repository. The revised ESP32 code has a much improved audio spectrum utilising the ESP32 much faster conversion time, I have been testing it today and find it can analyse frequencies well beyond 16KHz, unfortunately there is insufficient space on the screen to add another band, but I'm working on a smaller font to squeeze things in. Glad you like the software.
