### ISSUE TITLE
for loop, sample validities

### ISSUE THREAD

**Issue by erichiller** [G6EJD/ESP32-8266-Audio-Spectrum-Display#2]
Referencing [L60](https://github.com/G6EJD/ESP32-8266-Audio-Spectrum-Display/blob/7858326e5c7b80628c91dbf8bc73e534b2e9a16f/ESP8266_Spectrum_Display_01.ino#L60)
```c
    for (int i = 2; i < (SAMPLES/2); i++){ // Don't use sample 0 and only first SAMPLES/2 are usable. Each array eleement represents a frequency and its value the amplitude.
```
I entirely understand the reason behind not using sample **0** but wouldn't that mean that `i = 1` in the `for` loop rather than `i = 2`?

Is this an error or a fundamental understanding that I'm missing? I'm working on a similar project using a max4466. Thanks for these examples!

**Comment by G6EJD** [comment]
The FFT algorithm yields the fundamental in array[1] then all the harmonics in array[2] onwards

**Comment by erichiller** [comment]
I suppose my question is, wouldn't array[0] contain the fundamentals?

**Comment by G6EJD** [comment]
Array[0] contains the DC / offset value from zero, usually it would be 0. Array[1] contains the fundamental. Note the arrays used in my code are just the amplitude component of each frequency and the total frequency domain is determined by the sampling frequency.
