### ISSUE TITLE
Amplitude?

### ISSUE THREAD

**Issue by debsahu** [G6EJD/ESP32-8266-Audio-Spectrum-Display#3]
Firstly great project to get into sounds and ESP chips. What's the value of amplitude used for? How was the value of 50 set?

**Comment by debsahu** [comment]
I'm using a mic with 2V peak to peak. So amplitude is 2V*1024/3.3V = 620 ?

**Comment by G6EJD** [comment]
Amplitude is converted to bar height and is a nominal (not calibrated) value its more to visualise the spectrum and relative power levels. You could calibrate in software against some standard.

**Comment by debsahu** [comment]
Thanks!
